/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miVentana;

import ListaEnlazada.ListaLEG;
import ListaEnlazada.Nodo;
import Pila.ArrayPila;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miGestion.GestionarPostres;
import misClases.Ingrediente;
import misClases.Postre;
import util.Conectar;

/**
 *
 * @author Gherson
 */
public class AgregarPostre extends javax.swing.JInternalFrame {
DefaultTableModel modelo;
ListaLEG<Ingrediente> listaIngredientes;
    ArrayPila<Postre> listaPostre;
    GestionarPostres postre;
    
Postre pos;
    public AgregarPostre() {
        initComponents();
         listaIngredientes= new ListaLEG<>();
        postre = new GestionarPostres();
        listaPostre= new ArrayPila<>();
        postre =new GestionarPostres();
        jMostrar.setVisible(false);
        jMostrar1.setVisible(true);
        
        llenarcombo();

        listar();
    }
void listar()
     {
         for (int i = 100; i <= 500; i++)
         {
             if(i%50==0)
             {
             jCantidad.addItem(String.valueOf(i));
             }
         }
     }
  private void limpiar(){
       for (int i = 0; i < jTableIngredientes.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
   }
 private void llenarcombo()
 {      Conectar cn=new Conectar();        
        Connection cc=cn.conexion();
         String sql = "select * from ingredientes";
     try
     {
         Statement st=cc.createStatement();
            ResultSet rs=st.executeQuery(sql);      
            
         while(rs.next())
         {
             String ingre = rs.getString("nombre");
             jIngredientes.addItem(ingre);
         }
         
     }
     catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null,e);
             }
    
}
        
  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngredientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCantidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jAgregarIngrediente = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jIngredientes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMostrar = new javax.swing.JButton();
        jMostrar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jNomPostre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jAgregarPostre = new javax.swing.JButton();
        jEliminarPostre = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar Postre");

        jTableIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ));
        jTableIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableIngredientes);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredientes"));

        jLabel3.setText("Cantidad");

        jLabel4.setText("Nombre");
        jLabel4.setToolTipText("");

        jLabel5.setText("gr.");

        jAgregarIngrediente.setText("Agregar Ingrediente");
        jAgregarIngrediente.setToolTipText("");
        jAgregarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarIngredienteActionPerformed(evt);
            }
        });

        jEliminar.setText(" Eliminar Ingrediente");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jIngredientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija un ingrediente" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(jIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jAgregarIngrediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregarIngrediente)
                    .addComponent(jEliminar))
                .addContainerGap())
        );

        jLabel6.setText("Lista de Ingredientes");

        jLabel7.setText("Lista de Postres");

        jMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMostrarActionPerformed(evt);
            }
        });

        jMostrar1.setText("Mostrar Postres");
        jMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMostrar1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Postre"));

        jLabel1.setText("Codigo");
        jLabel1.setToolTipText("");

        jLabel2.setText("Nombre");

        jButton1.setText("Buscar Postre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNomPostre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNomPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jAgregarPostre.setText("Agregar Postre");
        jAgregarPostre.setToolTipText("");
        jAgregarPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarPostreActionPerformed(evt);
            }
        });

        jEliminarPostre.setText("Eliminar Postre");
        jEliminarPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarPostreActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAgregarPostre)
                                    .addComponent(jMostrar1))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLimpiar)
                                    .addComponent(jEliminarPostre))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMostrar)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jEliminarPostre)
                                    .addComponent(jAgregarPostre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jMostrar1)
                                    .addComponent(jLimpiar))
                                .addGap(16, 16, 16))
                            .addComponent(jMostrar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAgregarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarIngredienteActionPerformed
        String nombre = jIngredientes.getSelectedItem().toString();
        if(nombre.equalsIgnoreCase(""))
        {
             JOptionPane.showMessageDialog(this,"Ingrese un nombre por favor");
        }
        else
        {
 
        int cant=Integer.parseInt(jCantidad.getSelectedItem().toString());
        Ingrediente ingre =new Ingrediente(nombre,cant);
        listaIngredientes.agregarIngrediente(ingre);
        jCantidad.setSelectedIndex(0);
        jIngredientes.setSelectedIndex(0);

        jMostrarActionPerformed(evt);
        }
    }//GEN-LAST:event_jAgregarIngredienteActionPerformed

    private void jMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostrarActionPerformed

        String []titulo={"Nombre","Cantidad"};
        modelo=new DefaultTableModel(null,titulo);

        Nodo<Ingrediente> aux=listaIngredientes.getPrimero();
        while(aux!=null){
            modelo.addRow(new String[]{aux.getDato().getNombreIngrediente(),
                String.valueOf(aux.getDato().getCantidad())});

        aux=aux.getSiguiente();
        }
        jTableIngredientes.setModel(modelo);
    }//GEN-LAST:event_jMostrarActionPerformed

    private void jMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostrar1ActionPerformed

        jTextArea1.setText(postre.MostrarPostres());

    }//GEN-LAST:event_jMostrar1ActionPerformed

    private void jAgregarPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarPostreActionPerformed
        String codigo=jCodigo.getText();
        String nombre = jNomPostre.getText();
        if(nombre.equalsIgnoreCase("") && codigo.equalsIgnoreCase(""))
        {
             JOptionPane.showMessageDialog(this,"Ingrese los datos por favor");
        }
        else
        {
        pos=new Postre(codigo,nombre ,listaIngredientes);

        listaIngredientes= new ListaLEG<Ingrediente>();

        postre.agregarPostre(pos);
        jCodigo.setText("");
        jNomPostre.setText("");
        jMostrar1ActionPerformed(evt);
        limpiar();
        }
    }//GEN-LAST:event_jAgregarPostreActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed

        String nombre = jIngredientes.getSelectedItem().toString();
        listaIngredientes.eliminarIngrediente(nombre);
        jMostrarActionPerformed(evt);
        jCodigo.setText("");
        jIngredientes.setSelectedIndex(0);
        
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String []titulo={"Nombre","Cantidad"};
        modelo=new DefaultTableModel(null,titulo);
        String codigo = jCodigo.getText();

        if(codigo.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this,"Ingrese un codigo por favor");
        }else {
            Postre postrecito = postre.buscarPostre(codigo);
            if(postrecito!=null){
                jNomPostre.setText(postrecito.getNombrePostre());
                Nodo<Ingrediente> aux=postrecito.getListaIngrediente().getPrimero();
                while(aux!=null){
            modelo.addRow(new String[]{aux.getDato().getNombreIngrediente(),
                String.valueOf(aux.getDato().getCantidad())});

        aux=aux.getSiguiente();
        }
        jTableIngredientes.setModel(modelo); 
                

            } else {
                JOptionPane.showMessageDialog(this,"El codigo: "+codigo+" , no esta en la lista..");
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jEliminarPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarPostreActionPerformed
         String codigo = jCodigo.getText();

        if(codigo.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this,"Ingrese un codigo por favor");
        }else {
            Postre postrecito = postre.EliminarPostre(codigo);
            if(postrecito!=null){
                    JOptionPane.showMessageDialog(null,"Postre eliminado");
        }
             else {
                JOptionPane.showMessageDialog(this,"El codigo: "+codigo+" , no esta en la lista..");
            }
        }
        
        jLimpiarActionPerformed(evt);
    }//GEN-LAST:event_jEliminarPostreActionPerformed

    private void jTableIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableIngredientesMouseClicked
        int rec = this.jTableIngredientes.getSelectedRow();
        
        this.jIngredientes.setSelectedItem(jTableIngredientes.getValueAt(rec,0));
        this.jCantidad.setToolTipText(jTableIngredientes.getValueAt(rec,1).toString());
    }//GEN-LAST:event_jTableIngredientesMouseClicked

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
       jNomPostre.setText("");
       jCodigo.setText("");
       jIngredientes.setSelectedIndex(0);
       jCantidad.setSelectedIndex(0);
       jTextArea1.setText("");
       limpiar();
    }//GEN-LAST:event_jLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregarIngrediente;
    private javax.swing.JButton jAgregarPostre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCantidad;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JButton jEliminar;
    private javax.swing.JButton jEliminarPostre;
    private javax.swing.JComboBox<String> jIngredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JButton jMostrar;
    private javax.swing.JButton jMostrar1;
    private javax.swing.JTextField jNomPostre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableIngredientes;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
